<a href="https://colab.research.google.com/github/Wittig18/iris-classification-project/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from sklearn.datasets import load_iris # Import load_iris to load the Iris dataset
import pandas as pd # Import pandas for data manipulation
from sklearn.model_selection import train_test_split # Import train_test_split for splitting data into training and testing sets
from sklearn.linear_model import LogisticRegression # Import LogisticRegression for building the classification model
from sklearn.metrics import accuracy_score # Import accuracy_score for evaluating model performance

In [2]:
load_iris

<function sklearn.datasets._base.load_iris(*, return_X_y=False, as_frame=False)>

In [13]:
iris = pd.DataFrame(load_iris().data, columns= iris_feature)


In [14]:
iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [11]:
iris_feature = load_iris().feature_names

In [19]:
load_iris().target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
iris_target = load_iris().target
iris_data = load_iris().data

In [70]:
iris_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
iris_data_train, iris_data_test, iris_target_train, iris_target_test= train_test_split(iris_data, iris_target, test_size=0.2, random_state = 1)

In [29]:
iris_target_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2])

In [31]:
model = LogisticRegression()

In [32]:
model.fit(iris_data_train, iris_target_train)

LogisticRegression()

In [33]:
flower_pred = model.predict(iris_data_test)

In [76]:
# Get the target names (species names) from the Iris dataset
target_names = load_iris().target_names
# Loop through each prediction made by the model
for prediction in flower_pred:
    # Print the corresponding flower name using the prediction as an index
    print(target_names[prediction])

setosa
versicolor
versicolor
setosa
virginica
versicolor
virginica
setosa
setosa
virginica
versicolor
setosa
virginica
versicolor
versicolor
setosa
versicolor
versicolor
setosa
setosa
versicolor
versicolor
virginica
setosa
virginica
versicolor
setosa
setosa
versicolor
virginica


In [37]:
accuracy = accuracy_score(iris_target_test, flower_pred)

In [38]:
accuracy

0.9666666666666667

In [39]:
flower_new = [0.5,0.2,0.4,0.1] # checking model with new Data point


In [40]:
import numpy as np


In [41]:
flower = np.array(flower_new)

In [42]:
flower

array([0.5, 0.2, 0.4, 0.1])

In [45]:
flower_arr = flower.reshape(1,-1)

In [47]:
flower_name = model.predict(flower_arr)

In [48]:
for name in flower_name:
    print(target_names[name]) #looping to get the flower name

setosa


In [71]:
flower_2 = [5.9,	3.0,	5.1,	1.8]

In [72]:
flower_2 = np.array(flower_2)

In [73]:
flower_2

array([5.9, 3. , 5.1, 1.8])

In [74]:
flower_2 = flower_2.reshape(1,-1)

In [75]:
model.predict(flower_2)

array([2])

In [109]:
from google.colab import auth
auth.authenticate_user()

In [111]:
!git --version

git version 2.34.1
